spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: chatdb


server:
  port: 8089


custom:
  url:
    frontend-url: http://localhost:5173
  jwt:
    secretKey: javaSpringBootProjectProtectedKimYongJunStoreJsonWebTokenSecretKey